"""add_ingestion_pipeline_models

Revision ID: 51aea8fb6dae
Revises: 20260323_0002
Create Date: 2026-03-27 16:28:47.249360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51aea8fb6dae'
down_revision: Union[str, None] = '20260323_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_result_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('structured_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_extraction_results_job_id', table_name='extraction_results')
    op.drop_table('extraction_results')
    op.alter_column('audit_logs', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('audit_logs', 'payload_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_audit_logs_job_id', table_name='audit_logs')
    op.drop_constraint('audit_logs_job_id_fkey', 'audit_logs', type_='foreignkey')
    op.alter_column('canvas_versions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('canvas_versions', 'body_markdown',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('canvas_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_canvas_versions_job_id', table_name='canvas_versions')
    op.drop_constraint('canvas_versions_job_id_fkey', 'canvas_versions', type_='foreignkey')
    op.drop_constraint('canvas_versions_draft_id_fkey', 'canvas_versions', type_='foreignkey')
    op.drop_index('ix_chat_messages_session_created_at', table_name='chat_messages')
    op.drop_index('ix_chat_sessions_channel_thread', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_user_updated_at', table_name='chat_sessions')
    op.alter_column('drafts', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('draft', 'shared', 'archived', name='draftstatus'),
               existing_nullable=True)
    op.drop_index('ix_drafts_owner_created_at', table_name='drafts')
    op.drop_index('ix_drafts_source_id', table_name='drafts')
    op.alter_column('extracted_items', 'item_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('summary', 'decision', 'action_item', 'owner', 'due_date', 'question', 'blocker', name='itemtype'),
               existing_nullable=True)
    op.alter_column('extracted_items', 'confidence',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('high', 'medium', 'low', 'needs_review', name='confidence'),
               existing_nullable=True)
    op.drop_index('ix_extracted_items_draft_id', table_name='extracted_items')
    op.alter_column('ingestion_jobs', 'source_type',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('transcript_text', 'transcript_file', name='ingestionsourcetype'),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'provider_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('zoom', 'google_meet', 'teams', 'generic', name='providertype'),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'requested_mode',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('standard', 'detailed', 'summary', name='requestedmode'),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'status',
               existing_type=sa.VARCHAR(length=23),
               type_=sa.Enum('completed', 'failed', 'unsupported_source', 'fetching_source', 'fetched', 'cleaning_transcript', 'extracting_intelligence', 'rendering_canvas', 'received', 'classified', 'validated', 'queued', 'retrying', 'needs_permission', name='ingestionjobstatus'),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'progress_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ingestion_jobs', 'current_step',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ingestion_jobs', 'retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ingestion_jobs', 'failure_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ingestion_jobs', 'idempotency_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ingestion_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ingestion_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('ingestion_jobs_idempotency_key_key', 'ingestion_jobs', type_='unique')
    op.drop_index('ix_ingestion_jobs_channel_message', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_workspace_status', table_name='ingestion_jobs')
    op.create_index(op.f('ix_ingestion_jobs_idempotency_key'), 'ingestion_jobs', ['idempotency_key'], unique=True)
    op.drop_constraint('ingestion_jobs_workspace_id_fkey', 'ingestion_jobs', type_='foreignkey')
    op.drop_constraint('ingestion_jobs_user_id_fkey', 'ingestion_jobs', type_='foreignkey')
    op.alter_column('normalized_artifacts', 'text_content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('normalized_artifacts', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('normalized_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_normalized_artifacts_job_id', table_name='normalized_artifacts')
    op.drop_constraint('normalized_artifacts_job_id_fkey', 'normalized_artifacts', type_='foreignkey')
    op.alter_column('provider_access_records', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('provider_access_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('provider_access_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_provider_access_records_job_id', table_name='provider_access_records')
    op.drop_constraint('provider_access_records_job_id_fkey', 'provider_access_records', type_='foreignkey')
    op.alter_column('retry_records', 'error_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('retry_records', 'failure_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('retry_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_retry_records_job_id', table_name='retry_records')
    op.drop_constraint('retry_records_job_id_fkey', 'retry_records', type_='foreignkey')
    op.alter_column('shares', 'share_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('channel', 'user', name='sharetype'),
               existing_nullable=True)
    op.drop_index('ix_shares_draft_id', table_name='shares')
    op.alter_column('source_artifacts', 'text_content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('source_artifacts', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('source_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_source_artifacts_job_id', table_name='source_artifacts')
    op.drop_constraint('source_artifacts_job_id_fkey', 'source_artifacts', type_='foreignkey')
    op.alter_column('sources', 'source_type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('huddle_notes', 'text', 'csv', 'voice', 'thread', name='sourcetype'),
               existing_nullable=True)
    op.drop_index('ix_sources_channel_created_at', table_name='sources')
    op.drop_index('ix_sources_created_at', table_name='sources')
    op.alter_column('transcript_artifacts', 'transcript_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transcript_artifacts', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('transcript_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_transcript_artifacts_job_id', table_name='transcript_artifacts')
    op.drop_constraint('transcript_artifacts_job_id_fkey', 'transcript_artifacts', type_='foreignkey')
    op.drop_constraint('transcript_artifacts_source_artifact_id_fkey', 'transcript_artifacts', type_='foreignkey')
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key('transcript_artifacts_source_artifact_id_fkey', 'transcript_artifacts', 'source_artifacts', ['source_artifact_id'], ['id'])
    op.create_foreign_key('transcript_artifacts_job_id_fkey', 'transcript_artifacts', 'ingestion_jobs', ['job_id'], ['id'])
    op.create_index('ix_transcript_artifacts_job_id', 'transcript_artifacts', ['job_id'], unique=False)
    op.alter_column('transcript_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('transcript_artifacts', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('transcript_artifacts', 'transcript_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_sources_created_at', 'sources', ['created_at'], unique=False)
    op.create_index('ix_sources_channel_created_at', 'sources', ['slack_channel_id', 'created_at'], unique=False)
    op.alter_column('sources', 'source_type',
               existing_type=sa.Enum('huddle_notes', 'text', 'csv', 'voice', 'thread', name='sourcetype'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    op.create_foreign_key('source_artifacts_job_id_fkey', 'source_artifacts', 'ingestion_jobs', ['job_id'], ['id'])
    op.create_index('ix_source_artifacts_job_id', 'source_artifacts', ['job_id'], unique=False)
    op.alter_column('source_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('source_artifacts', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('source_artifacts', 'text_content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('ix_shares_draft_id', 'shares', ['draft_id'], unique=False)
    op.alter_column('shares', 'share_type',
               existing_type=sa.Enum('channel', 'user', name='sharetype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.create_foreign_key('retry_records_job_id_fkey', 'retry_records', 'ingestion_jobs', ['job_id'], ['id'])
    op.create_index('ix_retry_records_job_id', 'retry_records', ['job_id'], unique=False)
    op.alter_column('retry_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('retry_records', 'failure_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('retry_records', 'error_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key('provider_access_records_job_id_fkey', 'provider_access_records', 'ingestion_jobs', ['job_id'], ['id'])
    op.create_index('ix_provider_access_records_job_id', 'provider_access_records', ['job_id'], unique=False)
    op.alter_column('provider_access_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('provider_access_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('provider_access_records', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_foreign_key('normalized_artifacts_job_id_fkey', 'normalized_artifacts', 'ingestion_jobs', ['job_id'], ['id'])
    op.create_index('ix_normalized_artifacts_job_id', 'normalized_artifacts', ['job_id'], unique=False)
    op.alter_column('normalized_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('normalized_artifacts', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('normalized_artifacts', 'text_content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key('ingestion_jobs_user_id_fkey', 'ingestion_jobs', 'users', ['user_id'], ['id'])
    op.create_foreign_key('ingestion_jobs_workspace_id_fkey', 'ingestion_jobs', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_ingestion_jobs_idempotency_key'), table_name='ingestion_jobs')
    op.create_index('ix_ingestion_jobs_workspace_status', 'ingestion_jobs', ['workspace_id', 'status'], unique=False)
    op.create_index('ix_ingestion_jobs_channel_message', 'ingestion_jobs', ['slack_channel_id', 'slack_message_ts'], unique=False)
    op.create_unique_constraint('ingestion_jobs_idempotency_key_key', 'ingestion_jobs', ['idempotency_key'])
    op.alter_column('ingestion_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ingestion_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ingestion_jobs', 'idempotency_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ingestion_jobs', 'failure_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ingestion_jobs', 'retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ingestion_jobs', 'current_step',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ingestion_jobs', 'progress_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ingestion_jobs', 'status',
               existing_type=sa.Enum('completed', 'failed', 'unsupported_source', 'fetching_source', 'fetched', 'cleaning_transcript', 'extracting_intelligence', 'rendering_canvas', 'received', 'classified', 'validated', 'queued', 'retrying', 'needs_permission', name='ingestionjobstatus'),
               type_=sa.VARCHAR(length=23),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'requested_mode',
               existing_type=sa.Enum('standard', 'detailed', 'summary', name='requestedmode'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'provider_type',
               existing_type=sa.Enum('zoom', 'google_meet', 'teams', 'generic', name='providertype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'source_type',
               existing_type=sa.Enum('transcript_text', 'transcript_file', name='ingestionsourcetype'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)
    op.create_index('ix_extracted_items_draft_id', 'extracted_items', ['draft_id'], unique=False)
    op.alter_column('extracted_items', 'confidence',
               existing_type=sa.Enum('high', 'medium', 'low', 'needs_review', name='confidence'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    op.alter_column('extracted_items', 'item_type',
               existing_type=sa.Enum('summary', 'decision', 'action_item', 'owner', 'due_date', 'question', 'blocker', name='itemtype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.create_index('ix_drafts_source_id', 'drafts', ['source_id'], unique=False)
    op.create_index('ix_drafts_owner_created_at', 'drafts', ['owner_user_id', 'created_at'], unique=False)
    op.alter_column('drafts', 'status',
               existing_type=sa.Enum('draft', 'shared', 'archived', name='draftstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.create_index('ix_chat_sessions_user_updated_at', 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_index('ix_chat_sessions_channel_thread', 'chat_sessions', ['slack_channel_id', 'slack_thread_ts'], unique=False)
    op.create_index('ix_chat_messages_session_created_at', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_foreign_key('canvas_versions_draft_id_fkey', 'canvas_versions', 'drafts', ['draft_id'], ['id'])
    op.create_foreign_key('canvas_versions_job_id_fkey', 'canvas_versions', 'ingestion_jobs', ['job_id'], ['id'])
    op.create_index('ix_canvas_versions_job_id', 'canvas_versions', ['job_id'], unique=False)
    op.alter_column('canvas_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('canvas_versions', 'body_markdown',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('canvas_versions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key('audit_logs_job_id_fkey', 'audit_logs', 'ingestion_jobs', ['job_id'], ['id'])
    op.create_index('ix_audit_logs_job_id', 'audit_logs', ['job_id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('audit_logs', 'payload_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('audit_logs', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_table('extraction_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('draft_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('structured_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name='extraction_results_draft_id_fkey'),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], name='extraction_results_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='extraction_results_pkey')
    )
    op.create_index('ix_extraction_results_job_id', 'extraction_results', ['job_id'], unique=False)
    op.drop_table('extraction_result_records')
    # ### end Alembic commands ###
