# Canvas composer
from app.domain.schemas.extraction import ExtractionResult
from datetime import datetime

def create_draft_canvas(extraction: ExtractionResult) -> str:
    """Compose Slack Canvas markdown from extracted data."""
    title = f"Action Canvas — Meeting — {datetime.now().strftime('%Y-%m-%d')}"
    
    markdown = f"""# {title}
*Generated by ZManage | Source: huddle_notes | Confidence: {extraction.confidence_overall}*

## 📝 Summary
{extraction.summary}

## 🤝 Decisions Made
""" + "\n".join(f"- {d}" for d in extraction.decisions) + """

## ✅ Action Items
""" + "\n".join(
    f"- {item.content} (@{item.owner} if item.owner else 'Unassigned'}) {'📅 ' + str(item.due_date) if item.due_date else ''} {'⚠️ Needs Review' if item.confidence == 'needs_review' else ''}"
    for item in extraction.action_items
) + f"""

## ❓ Open Questions
""" + "\n".join(f"- {q}" for q in extraction.open_questions) + f"""

## 🚧 Blockers
""" + "\n".join(f"- {b}" for b in extraction.risks) + """

"""
    return markdown