from datetime import date, datetime

from app.domain.schemas.extraction import ActionItem, ExtractionResult, InsightItem


def create_draft_canvas(
    extraction: ExtractionResult, source_label: str = "huddle_notes"
) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    title = extraction.meeting_title or f"Meeting - {datetime.now().strftime('%Y-%m-%d')}"
    sections = [
        f"# Action Canvas - {title}",
        (
            "*Generated by ZManage | "
            f"Source: {source_label} | "
            f"Confidence: {extraction.confidence_overall.value}*"
        ),
        "",
        "## Tracking Snapshot",
        _render_snapshot_table(extraction, source_label, generated_at),
        "",
        "## Summary",
        extraction.summary or "No summary available.",
        "",
        "## Action Tracker",
        _render_action_items(extraction.action_items),
        "",
        "## Attention Log",
        _render_attention_log(extraction),
        "",
        "## Next Review Checklist",
        _render_review_checklist(extraction),
        "",
        "## Decision Register",
        _render_decisions(extraction.decisions),
    ]
    return "\n".join(sections).strip() + "\n"


def _render_snapshot_table(
    extraction: ExtractionResult, source_label: str, generated_at: str
) -> str:
    rows = [
        ["Status", extraction.status_summary or "Needs review"],
        ["Priority focus", extraction.priority_focus or "Confirm next steps and owners"],
        [
            "Next review",
            extraction.next_review_date.isoformat()
            if extraction.next_review_date
            else "Not set",
        ],
        ["Source", source_label],
        ["Generated", generated_at],
        ["Action items", str(len(extraction.action_items))],
        ["Attention items", str(len(extraction.open_questions) + len(extraction.risks))],
        ["Owners", ", ".join(extraction.owners) if extraction.owners else "Unassigned"],
    ]
    return _render_table(["Metric", "Value"], rows)


def _render_action_items(action_items: list[ActionItem]) -> str:
    if not action_items:
        return "- No action items captured yet."

    rows: list[list[str]] = []
    for index, item in enumerate(action_items, start=1):
        rows.append(
            [
                f"A{index}",
                item.content,
                item.owner or "Unassigned",
                item.due_date.isoformat() if item.due_date else "TBD",
                _action_status(item),
                _action_priority(item),
                "Add execution notes",
            ]
        )
    return _render_table(
        ["ID", "Action", "Owner", "Due", "Status", "Priority", "Notes"],
        rows,
    )


def _render_decisions(decisions: list[InsightItem]) -> str:
    if not decisions:
        return "- No decisions captured yet."

    rows = [
        [
            f"D{index}",
            item.content,
            "Communicate and confirm impact",
        ]
        for index, item in enumerate(decisions, start=1)
    ]
    return _render_table(["ID", "Decision", "Follow-up"], rows)


def _render_attention_log(extraction: ExtractionResult) -> str:
    rows: list[list[str]] = []
    for index, item in enumerate(extraction.risks, start=1):
        rows.append(
            [
                f"R{index}",
                "Risk",
                item.content,
                _risk_impact(item),
                "Assign mitigation owner",
            ]
        )
    for index, item in enumerate(extraction.open_questions, start=1):
        rows.append(
            [
                f"Q{index}",
                "Question",
                item.content,
                "Needs answer",
                "Resolve in next review",
            ]
        )
    if not rows:
        return "- No risks or open questions captured."
    return _render_table(["ID", "Type", "Item", "Status", "Next Step"], rows)


def _render_review_checklist(extraction: ExtractionResult) -> str:
    lines = [
        f"- [ ] Confirm {len(extraction.action_items)} action item(s) have clear owners and dates.",
        "- [ ] Update action statuses before the next review.",
        "- [ ] Clear or reclassify each item in the attention log.",
    ]
    if extraction.next_review_date:
        lines.append(
            f"- [ ] Run the next review on {extraction.next_review_date.isoformat()}."
        )
    return "\n".join(lines)


def _render_table(headers: list[str], rows: list[list[str]]) -> str:
    header_line = "| " + " | ".join(headers) + " |"
    divider_line = "| " + " | ".join(["---"] * len(headers)) + " |"
    body_lines = [
        "| " + " | ".join(_escape_cell(cell) for cell in row) + " |" for row in rows
    ]
    return "\n".join([header_line, divider_line, *body_lines])


def _escape_cell(value: str) -> str:
    return value.replace("\n", "<br>").replace("|", "\\|")


def _action_status(item: ActionItem) -> str:
    if not item.owner or not item.due_date:
        return "Needs detail"
    if item.confidence.value == "needs_review":
        return "Review"
    return "Ready"


def _action_priority(item: ActionItem) -> str:
    if not item.due_date:
        return "Medium"
    days_until_due = (item.due_date - date.today()).days
    if days_until_due <= 3:
        return "High"
    if days_until_due <= 7:
        return "Medium"
    return "Low"


def _risk_impact(item: InsightItem) -> str:
    if item.confidence.value == "high":
        return "High"
    if item.confidence.value == "medium":
        return "Medium"
    return "Review"
