from datetime import date, datetime

from app.domain.schemas.extraction import ActionItem, ExtractionResult, InsightItem


def create_draft_canvas(
    extraction: ExtractionResult, source_label: str = "huddle_notes"
) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    title = f"Action Canvas - Meeting - {datetime.now().strftime('%Y-%m-%d')}"
    sections = [
        f"# {title}",
        (
            "*Generated by ZManage | "
            f"Source: {source_label} | "
            f"Confidence: {extraction.confidence_overall.value}*"
        ),
        "",
        "## Tracking Snapshot",
        _render_snapshot_table(extraction, source_label, generated_at),
        "",
        "## Summary",
        extraction.summary or "No summary available.",
        "",
        "## What Happened",
        extraction.what_happened or extraction.summary or "No details available.",
        "",
        "## Action Tracker",
        _render_action_items(extraction.action_items),
        "",
        "## Decision Register",
        _render_decisions(extraction.decisions),
        "",
        "## Open Questions",
        _render_open_questions(extraction.open_questions),
        "",
        "## Risks And Blockers",
        _render_risks(extraction.risks),
        "",
        "## Ownership And Dates",
        _render_owner_date_summary(extraction),
        "",
        "## Next Review Checklist",
        _render_review_checklist(extraction),
        "",
        "## Notes For Manual Updates",
        "\n".join(
            [
                "- Update `Status`, `Priority`, and `Next Step` fields directly in the tables.",
                "- Add new rows as work progresses so the canvas stays current.",
                "- Use the checklist to track follow-up during the next meeting.",
            ]
        ),
    ]
    return "\n".join(sections).strip() + "\n"


def _render_snapshot_table(
    extraction: ExtractionResult, source_label: str, generated_at: str
) -> str:
    rows = [
        ["Source", source_label],
        ["Generated", generated_at],
        ["Overall confidence", extraction.confidence_overall.value],
        ["Action items", str(len(extraction.action_items))],
        ["Decisions", str(len(extraction.decisions))],
        ["Open questions", str(len(extraction.open_questions))],
        ["Risks", str(len(extraction.risks))],
    ]
    return _render_table(["Metric", "Value"], rows)


def _render_action_items(action_items: list[ActionItem]) -> str:
    if not action_items:
        return "- No action items captured yet."

    rows: list[list[str]] = []
    for index, item in enumerate(action_items, start=1):
        rows.append(
            [
                f"A{index}",
                item.content,
                item.owner or "Unassigned",
                item.due_date.isoformat() if item.due_date else "TBD",
                _action_status(item),
                _action_priority(item),
                item.confidence.value,
                "Add execution notes",
            ]
        )
    return _render_table(
        ["ID", "Action", "Owner", "Due", "Status", "Priority", "Confidence", "Notes"],
        rows,
    )


def _render_decisions(decisions: list[InsightItem]) -> str:
    if not decisions:
        return "- No decisions captured yet."

    rows = [
        [
            f"D{index}",
            item.content,
            item.confidence.value,
            "Communicate and confirm impact",
        ]
        for index, item in enumerate(decisions, start=1)
    ]
    return _render_table(["ID", "Decision", "Confidence", "Follow-up"], rows)


def _render_open_questions(open_questions: list[InsightItem]) -> str:
    if not open_questions:
        return "- No open questions captured."

    rows = [
        [
            f"Q{index}",
            item.content,
            "Assign owner",
            "Capture answer in next update",
            item.confidence.value,
        ]
        for index, item in enumerate(open_questions, start=1)
    ]
    return _render_table(["ID", "Question", "Owner", "Next Step", "Confidence"], rows)


def _render_risks(risks: list[InsightItem]) -> str:
    if not risks:
        return "- No active risks captured."

    rows = [
        [
            f"R{index}",
            item.content,
            _risk_impact(item),
            "Add mitigation owner and update",
            item.confidence.value,
        ]
        for index, item in enumerate(risks, start=1)
    ]
    return _render_table(["ID", "Risk", "Impact", "Mitigation", "Confidence"], rows)


def _render_owner_date_summary(extraction: ExtractionResult) -> str:
    owners = ", ".join(extraction.owners) if extraction.owners else "None captured"
    due_dates = (
        ", ".join(item.isoformat() for item in extraction.due_dates)
        if extraction.due_dates
        else "None captured"
    )
    rows = [
        ["Owners identified", owners],
        ["Due dates identified", due_dates],
        ["Latest due date", _latest_due_date(extraction)],
    ]
    return _render_table(["Tracking Field", "Current Value"], rows)


def _render_review_checklist(extraction: ExtractionResult) -> str:
    lines = [
        f"- [ ] Confirm {len(extraction.action_items)} action item(s) have clear owners.",
        "- [ ] Update statuses after the next working session.",
        "- [ ] Close answered questions and resolved risks.",
    ]
    if extraction.due_dates:
        lines.append(f"- [ ] Review deadlines before {_latest_due_date(extraction)}.")
    return "\n".join(lines)


def _render_table(headers: list[str], rows: list[list[str]]) -> str:
    header_line = "| " + " | ".join(headers) + " |"
    divider_line = "| " + " | ".join(["---"] * len(headers)) + " |"
    body_lines = [
        "| " + " | ".join(_escape_cell(cell) for cell in row) + " |" for row in rows
    ]
    return "\n".join([header_line, divider_line, *body_lines])


def _escape_cell(value: str) -> str:
    return value.replace("\n", "<br>").replace("|", "\\|")


def _action_status(item: ActionItem) -> str:
    if not item.owner or not item.due_date:
        return "Needs detail"
    if item.confidence.value == "needs_review":
        return "Review"
    return "Ready"


def _action_priority(item: ActionItem) -> str:
    if not item.due_date:
        return "Medium"
    days_until_due = (item.due_date - date.today()).days
    if days_until_due <= 3:
        return "High"
    if days_until_due <= 7:
        return "Medium"
    return "Low"


def _risk_impact(item: InsightItem) -> str:
    if item.confidence.value == "high":
        return "High"
    if item.confidence.value == "medium":
        return "Medium"
    return "Review"


def _latest_due_date(extraction: ExtractionResult) -> str:
    if not extraction.due_dates:
        return "None captured"
    return max(extraction.due_dates).isoformat()
